-- ==================================
-- Total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM products
GROUP BY category
ORDER BY total_products DESC;

-- the average costs in each category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM products
GROUP BY category
ORDER BY avg_cost DESC;

-- Total revenue generated for each category
SELECT
    p.category,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN products p
    ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN customers c
    ON c.customer_key = s.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- The distribution of sold items across countries
SELECT
    c.country,
    SUM(s.quantity) AS total_sold_items
FROM sales s
LEFT JOIN customers c
    ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
